### ISSUE TITLE
メソッドの一覧が読み取りづらい

### ISSUE THREAD

**Issue by pocke** [rurema/bitclust#102]
# Problem

るりまのドキュメントのクラスのページにそのクラスで定義されているメソッドの一覧がありますが、メソッド間の空白が狭いせいかとても読みづらく感じます。

![200225024719](https://user-images.githubusercontent.com/4361134/75177321-421bd100-5779-11ea-9e43-354a3f7014a2.png)

そのため、これをもう少し読みやすくしたいです。

# Solution

試しにmarginを入れてみたところ、だいぶ読みやすくなった気がします。

`margin-left: 10px`

![200225024507](https://user-images.githubusercontent.com/4361134/75177365-595abe80-5779-11ea-8ece-10a7f768e508.png)

`margin-left: 5px`

![200225025020](https://user-images.githubusercontent.com/4361134/75177489-9921a600-5779-11ea-9b87-e28278b52b96.png)

10pxだと間隔が少し広すぎると感じるので、5pxのほうがちょうどよいと思っています。
5pxのmarginを足そうと思うのですが、どうでしょうか？

margin以外にもなにか良いアイディアがあればコメントください！
とはいえ、marginを入れるのは一瞬でできるし、とりあえず一次対応としてやってしまって良いかなと思っています。それ以上の改善はmarginを入れてから考えるので遅くないと思っています

**Comment by pocke** [comment]
https://twitter.com/r7kamura/status/1232001797713059841

```
+ / <=> == ===
absolute? ascend atime
basename binread binwrite birthtime blockdev?
chardev? children chmod chown cleanpath ctime
...
```

みたいに先頭1文字でグルーピングして並べるのはありかもしれない。ただ、クラスによっては不自然にガタガタしたリストができるかなあ…。

**Comment by scivola** [comment]
この手のリストは多段組が見やすいと思うので，サンプルを作ってみました。

![method-TOC](https://user-images.githubusercontent.com/294125/75199653-f97b0c80-57a6-11ea-9425-4f61b4a84cd1.png)

当然ながら面積を喰います。
また，欠点を示すためにわざとメソッド名が 2 行に折れている例（`each_with_index` と `each_with_object`）を入れておきました。
メソッド名が途中で改行されちゃうのは，やはり見づらいですね。「なんだ？　この `x` や `ct` は？」って思いませんでしたか？
これを防ぐ（減らす）ためにはカラムの幅を広めに取る必要がありますが（このサンプルはわざと狭めにしてある），そうするとますます面積を喰います。
このあたりはトレードオフでしょうか。

このサンプルを見て改めて感じましたが，エイリアスを隣接させているため，リストが純粋な ABC 順になっていなくて何順なのか分かりにくいですね。
エイリアスであることはジャンプ先で分かれば十分なので，一覧ではバラして完全に ABC 順にするのはどうでしょうか。

**Comment by pocke** [comment]
おおー、よさそう👏 
しばらく待って他に案がなければこれでいきますかね。
その際は実装までお願いできるでしょうか？

> エイリアスであることはジャンプ先で分かれば十分なので，一覧ではバラして完全に ABC 順にするのはどうでしょうか。

良いと思います！

**Comment by scivola** [comment]
>  その際は実装までお願いできるでしょうか？

BitClust がさっぱり分からないのですが，

- bitclust/data/bitclust/template/
- bitclust/theme/default/

の中身をいじればいいのでしょうか？
テーマには lillia というのもあるようですが，こちらも？
また，テンプレートには *.epub と *.offline もありますが，これらも？

手許で確認するためには出来上がりを見ないといけませんが，bitclust コマンドは実は

```
bitclust htmlfile 
```

以外をほぼ使ったことがなく，よく分からないので，そこらへんから勉強です。

**Comment by pocke** [comment]
> BitClust がさっぱり分からないのですが，



すみません、パッと説明できるほどにまとまってないので、Contribution Guideなどを作ってまとめようと思います！ しばしお待ちください🙏

**Comment by scivola** [comment]
プルリクエストが取り込まれたので，ひとまず閉じていただいていいのではと思います。

**Comment by hanachin** [comment]
プルリクエストありがとうございました。Closeします。
