### ISSUE TITLE
BitClustのシンタックスハイライト機能が終端なしのRangeに対応していない

### ISSUE THREAD

**Issue by taki** [rurema/bitclust#108]
https://github.com/clear-code/rurema-search/issues/31 からの報告です。

@kou さんがおっしゃるにはシンタックスハイライト機能には以下の問題があるらしいです。

> これ、BitClustのシンタックスハイライト機能が終端なしのRangeに対応していなくてエラーになるからなんですよ。
> rurema/doctree@55e28e0#diff-3b8de3267235fda393d0c1ea268bf05aR45 で追加されたサンプルコードでエラーが発生します。
> 終端を持たない範囲オブジェクト:3:6 syntax error, unexpected ')' (BitClust::SyntaxHighlighter::ParseError)
> 後でBitClustを直そうと思って全然手を付けられていないのでBitClustの方に報告しておいてもらえますか？

**Comment by pocke** [comment]
> これ、BitClustのシンタックスハイライト機能が終端なしのRangeに対応していなくてエラーになるからなんですよ。

BitClustが終端なしのRangeに対応していないわけではありません。BitClustはシンタックスハイライトにRipperを使っており、RipperはランタイムのRubyのバージョンに依存してパースできる文が決まります。
なのでるりまサーチを動かしているサーバーのRubyのバージョンを上げると解決すると思われます。

**Comment by pocke** [comment]
syntax errorがあってもそれっぽくハイライトできるようにする、というのはありかもしれません。新しい構文のドキュメントを書こうとする度に起こる問題ですし。
その場合syntax errorに気がつけなくなると悲しいので、何らかの仕組みで気が付けるようにはしておきたいですね。

**Comment by kou** [comment]
なるほど。

るりまサーチで使っているRubyはできればAPTでインストールできるバージョンを使いたいので、このケースのためにRubyのバージョンは上げたくありません。

#109 のようにオプションを指定したときだけシンタックスハイライトに失敗したらソースそのものを表示するのはどうですか？オプションを指定しないときは既存の動作と変わりません。
