### ISSUE TITLE
chmファイルで文字化けが発生します。

### ISSUE THREAD

**Issue by dogatana** [rurema/bitclust#19]
HTML Help Workshop用ファイルのエンコーディングが utf-8 のため文字化けが発生します。

lib\bitclust\subcommands\chm_command.rb で Windows-31j を指定すれば良いのですが、
pull request を発行するのが良いでしょうか？

**Comment by okkez** [comment]
kconv というロストテクノロジーが使われているので最近のRubyだと書いた当時の意図通りには動かないかもしれません。
CHMを作るためのexeが正規ルートではもう手に入らないので、自分はこの機能をもうメンテナンスできないです。
PR貰えば、レビューしてマージするのはできますが、動作確認等はできないです。

とりあえず、https://github.com/rurema/bitclust/blob/master/lib/bitclust/subcommands/chm_command.rb#L256 の create_file でエンコーディングを適切に扱うようにすれば動くような気はします。

**Comment by dogatana** [comment]
kconv ではなく、1.8 以前デフォルトのエンコーディングが変わったためではないでしょうか。
（以前はCP932 がデフォルトで問題がなかったのでは？）

CHM作成ツールはMicrosoft のWebページから入手可能ですね。
むしろ環境としてCHMはWindowsで非推奨になってしまっているのが問題かもしれません。

なおWorkshop用ファイル（*.hh?）だけでなく、本文側のHTMLもShift_JISとしないと日本語による検索ができないようなので、ちゃんと取り組むならもう少し調べる必要があるのが分かりました。
今の文章は一部 String#encode で例外が発生する文字が含まれているので。。

**Comment by okkez** [comment]
> CHM作成ツールはMicrosoft のWebページから入手可能ですね。

私が以前探したときは見つからなくて、↓のように非推奨だからダウンロードできなくしたのだと思っていました。
たしか exe の名前で検索をgoogleやらMSのサイト内検索やらを試した覚えがあります。
マイクロソフトはURLを変更することが度々あるので、探し方とリンク先を教えてもらえないでしょうか。

> むしろ環境としてCHMはWindowsで非推奨になってしまっているのが問題かもしれません。

**Comment by dogatana** [comment]
> 探し方とリンク先

html help workshop で検索すると出てきます。
現在出てくるのは次のリンクでした
https://msdn.microsoft.com/ja-jp/library/windows/desktop/ms669985(v=vs.85).aspx
GUI ツール (hhw.exe) の他、コマンドラインツール(hhc.exe) も含まれています。

目次が文字化けせず、日本語による検索も可能にしたつもりのものを pull request しました。

**Comment by dogatana** [comment]
master ブランチに修正を加えてしまってますが、別のブランチ（トピックブランチというのでしょうか）を切ってからの方が良かったのかもしれません。。

**Comment by okkez** [comment]
プルリクエストするときは、トピックブランチを切るのが望ましいですが master ブランチからプルリクエストしても特に問題はありませんよー。

#20

**Comment by okkez** [comment]
#20 をマージしたので閉じます。ありがとうございました。
