### ISSUE TITLE
rake test が失敗します (windows 環境）

### ISSUE THREAD

**Issue by dogatana** [rurema/bitclust#21]
gem としては

> gem list test
*** LOCAL GEMS ***
minitest (5.8.3)
rubytest (0.8.1)
test (1.0.0)
test-unit (3.2.1, 3.1.5)

が入っていますが、次のように失敗します。

> rake test
ruby test/run_test.rb
C:/Programs/Ruby/lib/ruby/site_ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require': cannot load such file -- test/unit/notify (LoadError)
        from C:/Programs/Ruby/lib/ruby/site_ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
        from test/run_test.rb:6:in `<main>'
rake aborted!
Command failed with status (1): [ruby test/run_test.rb...]
C:/Git/bitclust/Rakefile:15:in `block in <top (required)>'
Tasks: TOP => test
(See full trace by running task with --trace)

テストスイーツが異なるためではないかと思うのですが、どの gem を入れれば良いでしょうか。

環境
ruby 2.3.0p0 (2015-12-25 revision 53290) [i386-mingw32]
Windows 10 Pro 64bit

**Comment by okkez** [comment]
エラーメッセージにあるとおり test-unit-notify を入れてください。

**Comment by dogatana** [comment]
ありがとうございます。

test/unit/notify が test-unit-notify と言うことに思い至りませんでした。
このあと、test-unit-rr もインストールして test が実行できるようになりました。

**Comment by okkez** [comment]
`bundle install` をすれば開発に必要なgemがインストールできることを忘れていました。。。

**Comment by dogatana** [comment]
恥ずかしながら bundle を使った事が無いのですが、そういうことができるのですね。

gem でも依存関係を確認するのができるのを、今日知りました ^^;
> gem d bitclust-core                  
Gem bitclust-core-0.9.2                
  progressbar (>= 0)                   
  rack (>= 0)                          
  test-unit (>= 2.3.0, development)    
  test-unit-notify (>= 0, development) 
  test-unit-rr (>= 0, development)
