### ISSUE TITLE
samplecode の末尾が出力されないことがある

### ISSUE THREAD

**Issue by znz** [rurema/bitclust#46]
https://github.com/rurema/doctree/pull/974 の変更をしていて気づいたのですが、

```
#@samplecode 例
require 'pp'

b = [1, 2, 3] * 4
a = [b, b]
a << a
pp a

#=> [[1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3],
     [1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3],
     [...]]
#@end
```

で `     [...]]` の行が HTML に出力されないようです。

**Comment by sho-h** [comment]
以下の1行目のサンプルのような `{` と `}` のミスマッチが起こるケースもあるみたいでした。

* https://docs.ruby-lang.org/ja/2.5.0/method/Array/i/sort_by=21.html

**Comment by okkez** [comment]
一つ目の例はたぶん SyntaxError になっていて出力されないんだと思いました。
以下のようにすればちゃんと出ます。

```ruby
#@samplecode example
require 'pp'

b = [1, 2, 3] * 4
a = [b, b]
a << a
pp a # => [[1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3],
     #     [1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3],
     #     [...]]
#@end
```

**Comment by znz** [comment]
黙って無視されると、ちゃんと出力されているかどうか毎回目視確認が必要になって大変なので、エラーの時は無視するのではなく変換時にエラーで止まってほしいです。

**Comment by okkez** [comment]
`Ripper::Filter` ベースだと素直な方法では実現できなくて悩んでます。。。

**Comment by pocke** [comment]
https://github.com/rurema/bitclust/pull/50 でsyntax checkされるようになったので、このIssueはcloseできそうですね

**Comment by znz** [comment]
試してみたところ `BitClust::SyntaxHighlighter::ParseError` で止まってくれたので良さそうです。
