### ISSUE TITLE
Mac + Chrome 環境でサンプルコードが等幅にならずに表示がずれる

### ISSUE THREAD

**Issue by tbpgr** [rurema/bitclust#51]
Mac + Chrome 環境でサンプルコードが等幅にならずに表示がずれます

例えば

https://docs.ruby-lang.org/ja/latest/method/String/s/new.html

![image](https://user-images.githubusercontent.com/4787509/36311537-eef4f420-136e-11e8-9810-f377d6cf71f1.png)

Mac  + Chrome でコメントが揃わない。

同じ内容を↓のように esa で確認するとズレてないし、Win + Chrome も問題ない。

```ruby
text = "hoge".encode("EUC-JP")
no_option = String.new(text)                             # => "hoge"
no_option.encoding == Encoding::EUC_JP                   # => true
with_encoding = String.new(text, encoding: "UTF-8")      # => "hoge"
with_encoding.encoding == Encoding::UTF_8                # => true
String.new("test", encoding: "UTF-8", capacity: 100_000) # => "test"
```

* Win + Chrome 

![image](https://user-images.githubusercontent.com/4787509/36311548-f608d812-136e-11e8-9d50-4053f238bbee.png)

## 原因
https://qiita.com/tmsanrinsha/items/d493a9889df7dee239bb

たぶんこれ？
（ [hkdnet](https://twitter.com/hkdnet) さんと [becolomochi](https://twitter.com/becolomochi)  ）さんに調べてもらった。

**Comment by hazi** [comment]
この問題に関してですが、macOS Safari, Dash などでも同様の状況で、ブラウザ固有の問題ではなくシステムレベルで対応が行えていないのだと思います。

検索すると色々な対応策が出てきますが、CSSがシンプルで普段使っていて特に不満のない GitHub の CSS を参考に下記のようにしてはどうかと思うのですが、如何でしょうか。

試しにローカルでやってみました

style.css
```diff
15a16,20
> code, pre, tt {
>   font-size: 90%;
>   font-family: SFMono-Regular, Consolas, Liberation Mono, Menlo, monospace;
> }
> 
233,236d237
< code {
<     font-family: monospace;
< }
< 
```

macOS 10.14.6 / Safari 12.1.2

before
<img width="491" alt="before" src="https://user-images.githubusercontent.com/5656927/64753569-a85fbf00-d55e-11e9-814d-5f34856dceac.png">

after
<img width="577" alt="after" src="https://user-images.githubusercontent.com/5656927/64753597-be6d7f80-d55e-11e9-83bb-880e38a60856.png">

**Comment by hanachin** [comment]
なおっていそうなので閉じます!
