### ISSUE TITLE
samplecode で横スクロール

### ISSUE THREAD

**Issue by znz** [rurema/bitclust#55]
https://docs.ruby-lang.org/ja/latest/method/Exception/i/full_message.html
のように実行結果が長いと横スクロールが発生してしまいます。

ブログなどでよくあるようにコード部分だけ横スクロールするようにして、ページ全体は横スクロールバーが発生しないようにするのはどうでしょうか?

**Comment by scivola** [comment]
動作確認はしていないもののたぶんこれでいいんだと思うのですが。

```diff
--- a/theme/default/style.css
+++ b/theme/default/style.css
@@ -126,6 +126,7 @@ pre.highlight {
     padding: 0px 10px 10px 10px;
     font-weight: normal;
     position: relative;
+    overflow: auto;
 }

 pre .caption {
```

**Comment by okkez** [comment]
`overflow-x: auto;` でいいのでは。

**Comment by scivola** [comment]
いまの場合，`overflow` でも `overflow-x` でもどっちでもいいと思います。

`overflow-x: auto` の場合，`overflow-y` が `visible`（既定値）だと `auto` の扱いになるようです。
https://developer.mozilla.org/ja/docs/Web/CSS/overflow-x
なのでどちらでも同じ結果に。

**Comment by hanachin** [comment]
#76 で `overflow: auto;` 設定してみました

**Comment by hanachin** [comment]
#76 で横スクロールできるようになったので、閉じます
