### ISSUE TITLE
gemのリリースできる人を追加したい

### ISSUE THREAD

**Issue by okkez** [rurema/bitclust#68]
あんまりアクティブに活動できてなくて、gemのリリースが滞っていると思うのでgemのリリースをできる人を追加したい。
「やるぞ！」という気持ちの人は手を上げてください。

:thought_balloon: 9月10月あたりは比較的マシなのでなんかできるかも。

**Comment by znz** [comment]
そのうち GitHub Actions でタグをうったら自動リリースとかやってみたいです。
まだベータさえ来てないので、普通に手動でリリースを試してみることからになりそうですが、やりたいです。

**Comment by okkez** [comment]
bitclust-core, bitclust-dev, refe2 の3つに追加しておきました！

**Comment by sho-h** [comment]
ラベル追加して(マイルストーンのがよかったかもですけど、)、 #69 を作成してみました。

**Comment by okkez** [comment]
12月になったけど znz さん以外手が上がってないので閉じます
