### ISSUE TITLE
クラスのメソッド目次に、継承元で定義されているメソッドへのリンクも欲しい

### ISSUE THREAD

**Issue by pocke** [rurema/bitclust#72]
# 問題

たとえば`Array#count`のようなメソッドは、るりまのドキュメントではArrayのページには説明が存在せず、`Enumerable#count`として存在している。
一方`Array#sum`はArrayにもEnumerableにも両方存在している。

初心者としては(というか私のようなある程度Rubyに慣れた人間でも)これは混乱の元で、ドキュメントを探すのがちょっと大変。
なぜならばドキュメントを探すためにRubyのメソッドの実装を意識しなければならないため。

# 解決案

目次の部分に、継承元のメソッドを表示するようにしたい。

例: (これはWebコンソールで適当にいじったやつなので、実装はまだ何もないです)

![190930165120](https://user-images.githubusercontent.com/4361134/65859752-d6892f80-e3a3-11e9-8f03-acd4e219b735.png)

「Enumerableで定義されているメソッド」の中のリンクはEnumerableのページへのリンクで、Arrayのページ内にメソッドの解説まで書く必要はないと思っています。
つまり、単にページ先頭にメソッド一覧へのリンクを作れば良いかなと言う提案です。

**Comment by znz** [comment]
参考のために javadoc を適当に探してみたら、こんな感じでした。

https://docs.oracle.com/javase/jp/8/docs/api/java/lang/String.html#methods.inherited.from.class.java.lang.Object

<img width="556" alt="スクリーンショット 2019-09-30 17 06 00" src="https://user-images.githubusercontent.com/11857/65860153-34445a00-e359-11e9-8133-f554221b254a.png">

**Comment by hazi** [comment]
どこまで継承をたどるか、extendは含めるかと言うのも議題ですかね。

継承は
- BasicObject から全部出すか
- Object以下に絞るか（Objectを含む）
- Objectより下に絞るか（Objectは含まない）
- 一つ上の親までに絞るか

最後は微妙かな。
javadoc は Object から出すのか…

継承リスト例
- `Array`: Array < Enumerable < Object < Kernel < BasicObject
- `Integer`: Integer < Numeric < Comparable < Object < Kernel < BasicObject
- `ClosedQueueError`: ClosedQueueError < StopIteration < IndexError < StandardError < Exception < Object < Kernel < BasicObject

そういえば、`Enumerable` だいたい継承リストに入ってるけど、
extend ですよね。[`ENV`](https://docs.ruby-lang.org/ja/2.6.0/class/ENV.html) は extend に書かれてる。
この辺りも整理しないとチグハグになりそう。

**Comment by hanachin** [comment]
#73 で表示されるようになったので、閉じます
