### ISSUE TITLE
配布されているアーカイブ (ruby-refm-1.9.3-dynamic-20120829) の server.rb で何も表示されない

### ISSUE THREAD

**Issue by znz** [rurema/bitclust#8]
http://cache.ruby-lang.org/pub/ruby/doc/ から ruby-refm-1.9.3-dynamic-20120829.tar.xz をダウンロードして `ruby server.rb` を実行して `http://localhost:10080/` を開いても真っ白なページで内容が表示されません。

原因を調べてみたところ、 https://github.com/rurema/bitclust/commit/f42aba092874544eed5d5d46bfe0ec6e2e65ebb5 の変更で `db` の代わりに `@database_prefix` になったのに初期値が設定されていないのが原因のようです。

とりあえず

``` bash
mkdir -p ~/.bitclust
echo ':database_prefix: db' > ~/.bitclust/config
```

のように `~/.bitclust/config` で設定すれば表示されるようになりました。

**Comment by hanachin** [comment]
server.rb、今は使われてなさそうなので、閉じちゃいます
