### ISSUE TITLE
Firefox での header nav ol の表示が違う

### ISSUE THREAD

**Issue by znz** [rurema/bitclust#87]
https://docs.ruby-lang.org/ja/latest/class/File.html が macOS の Firefox 71 だと以下のように ol そのままでスタイルシートが適用されていないような感じの表示がされています。

<img width="780" alt="スクリーンショット 2019-12-06 13 21 28" src="https://user-images.githubusercontent.com/11857/70295730-f2fc7a80-17df-11ea-8d16-8e7fdacfa5f2.png">

Chrome だと以下のように表示されています。

<img width="799" alt="スクリーンショット 2019-12-06 13 23 51" src="https://user-images.githubusercontent.com/11857/70295829-3d7df700-17e0-11ea-812b-73eed864a850.png">

**Comment by hanachin** [comment]
Chromeでもそうですね

![Screenshot from 2019-12-06 13-28-37](https://user-images.githubusercontent.com/167012/70295997-58765880-182c-11ea-9db5-4edd72441a83.png)

https://docs.ruby-lang.org/ja/latest/style.css のキャッシュがまだ残っていて更新されていなさそうです

**Comment by znz** [comment]
調査ありがとうございます。
ピンポイントで purge するなら権限がなくてもできそうだったので `curl -X PURGE -H "Fastly-Soft-Purge:1" https://docs.ruby-lang.org/ja/latest/style.css` を実行してみたところ更新されたようなので、閉じます。
