### ISSUE TITLE
フィードバックリンクの改善

### ISSUE THREAD

**Issue by znz** [rurema/bitclust#92]
#18 でリンクは追加されましたが、さらに改善できると良さそうです。

参考: https://jsprimer.net/intro/feedback/

テンプレートとして参照していたページの URL が入るようなサイトもあるようなので、そういうリンクにするのも良さそうです。

**Comment by hanachin** [comment]
#133 でマニュアルを生成する際に参照していたファイルをGitHubで編集するためのリンクを追加してみました

**Comment by znz** [comment]
edit link が追加されたので close します。
