### ISSUE TITLE
meta情報のtitleから"instance method"などの表記をなくしたい

### ISSUE THREAD

**Issue by pocke** [rurema/bitclust#93]
# problem

現在、るりまのメソッドページのタイトルには最初に「instance method」などの文字列が入っています。

![191229211507](https://user-images.githubusercontent.com/4361134/71557179-e5a47a00-2a85-11ea-8906-8ed1d1c06082.png)

メソッドがinstance methodなのかどうかというのはクラス名とメソッド名が`#`で繋がれているのを見れば分かるので、あまり重要な情報ではありません。それなのに「instance method」が一番先頭に来ているのは、違和感があります。

# solution

そのため、タイトル情報から"instance method"という表記をなくす or 後ろに移すのを提案します。

実際のメソッドページに表示されている青帯の部分は変えても変えなくても良いかなと思っています。
![191229215519](https://user-images.githubusercontent.com/4361134/71557186-f94fe080-2a85-11ea-80c7-cf4a4c6781e4.png)

# その他

これってSEOに効果あるんですかね、わからない🤔

**Comment by hanachin** [comment]
もしも同じクラスに同じ名前のクラスメソッド・インスタンスメソッド・モジュール関数があるとtitleの記号だけでしか区別がつかなくなる? (あるのかは確認してないです)

**Comment by znz** [comment]
開いて内容をみれば区別できるのなら、タイトルは簡潔にしても良さそうです。
rdoc はどうだっけ、と思ったらメソッド個別ページがないので、比較できませんでした。

**Comment by pocke** [comment]
メモ: クラスやモジュールのページはタイトルにclass, moduleを含んだままのほうが良さそうに思いました。メソッドと違って # で区別できないし、短いのでそこまで邪魔にもならなさそう

**Comment by pocke** [comment]
> もしも同じクラスに同じ名前のクラスメソッド・インスタンスメソッド・モジュール関数があるとtitleの記号だけでしか区別がつかなくなる? (あるのかは確認してないです)



`Hash#[]`と`Hash.[]`は思いつきましたが、普通のメソッド名だと何かあったかな……。

ページを見に行けば分かるし、おそらくレアケースなので実際に遭遇することは中々ないから大丈夫なんじゃと思っています。
