### ISSUE TITLE
refe2のgemspecにmetadataを記載する

### ISSUE THREAD

**Issue by hanachin** [rurema/bitclust#99]
> scivola  22:35
> https://rubygems.org/gems/refe2
> の「ソースコード」がリンク切れになっていますね。
https://ruby-jp.slack.com/archives/CM3PCPNQ5/p1581946508272300

この辺書くとよさそう
https://guides.rubygems.org/specification-reference/#metadata

**Comment by znz** [comment]
1.2.5 をリリースして更新されていることを確認しました。
